#----------------------------------------------------
VERSION = '0.19_dqn_zeroLstm_reduced_action_set'

VERSION_FOLDER = './v_' + VERSION + '/'
DATABASE_NAME = VERSION_FOLDER + 'DS3Experiences_' + VERSION
TRAINING_DATA_DATABASE_NAME = VERSION_FOLDER + 'Training_data_logs_' + VERSION
CSV_NAME = VERSION_FOLDER + 'playground_state_' + VERSION + '.csv'
TRAINING_DATA_TABLE = 'Training'
TRAINING_EXPERIENCES_DATA_TABLE = 'Experiences'

IMAGE_SIZE = (1280,720,3)
IMAGE_WIDTH = 1280
IMAGE_HEIGHT = 720
IMAGE_SHAPE = (150,93,3)
NUMBER_OF_ACTIONS = 5
MIN_ACTIONS = 10
MAX_ACTIONS = 200


# HYPERPARAMETERS
GAMMA = 0.99

LEARNING_RATE = 0.0001

EPSILON_MIN = 0.1

EPSILON_MAX = 1.0

EPSILON_DECAY_RATE = 0.0001

BATCH_SIZE = 32

MAX_STEPS_PER_EPISODE = 200

FRAME_STACK = 4

STACKED_IMAGE_SHAPE =  IMAGE_SHAPE[:-1] + (FRAME_STACK*IMAGE_SHAPE[-1],)

OBSCURING_FACTOR = 1/60 * FRAME_STACK # the k talking in dqn papers

Q_NET_TARGET_UPDATE_INTERVAL = 10

# TRAINING PARAMETERS
